---
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web_hook'  # require some tunning

receivers:
  - name: 'web_hook'
    webhook_configs:
      - url: 'http://example.com/alerts'  # require some tunning
