groups:
  - name: demo_alerts
    rules:
      - alert: HighDataProcessingFailures
        expr: |
          increase(demo_push_gateway_process_events_total{event_type="EventType.DATA_PROCESSING", status="EventStatus.FAILURE"}[1m]) == 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "High number of data processing failures detected"
          description: "There have been more than 0 data processing failures in the last 1 minute."
