---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "demoapp"
    static_configs:
      - targets: ["host.docker.internal:8880"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "pushgateway"
    static_configs:
      - targets: ["pushgateway:9091"]
    relabel_configs:
      - source_labels: [__address__]
        regex: "(.*)"
        target_label: instance
        replacement: pushgateway

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
